lib-test: lib-test.c
	gcc -I../include  -I../../glu-1.3/include -o lib-test lib-test.c -L. -L.. -L../glu-1.3 -L../../glu-1.3 -L/usr/X11R6/lib -L/users/fmang/software/tcltk/lib/ -L/users/fmang/software/tcltk/lib/ -L/users/fmang/software/tcltk/lib/ -L/usr/lib -lmocha -lcu -lglu -ltk4.2 -ltcl7.6 -ltix4.1 -lX11 -lm  -lfl  -lnsl -lrpcsvc -ldl 

