#Makefile for the portal by Vaibhav

put:	
	@echo "Making pulic"
	@chmod -R 755 *
	@scp -r * vitraag@zexxxx.genotrance.com:public_html

putcse:
	@echo "Making pulic in cse dir..."
	@chmod -R 755 *	
	@scp -r * vaibhav@cse.ucsc.edu:.html/vitraag/

			
