#!/usr/bin/perl

#Author: Vaibhav<vaibhav@cse.ucsc.edu>
#Adds the tag substitutions to all html files
#$id$

#################Portability and Displacment Variables##########
$portal = ".";

#######################HTML SUBSTITUTIONS#######################
#The new banner
$banner = qq!<\!--start-banner-->
    <\!--Generated by makeBanner.pl-->
    <div class="banner">
    <p><a href="$portal"><img src="$portal/images/vitraag.png"></a></td>
    <a href="$portal">Web-based FFS</a></td>
    <a href="$portal/pb/index.html">Pragat Bharat</a></td>
    </div>
    <\!--end-banner-->
!;

$address = qq!<\!--start-address-->
    <\!--Generated by makeBanner.pl-->
    <hr><address><a href ="mailto:vaibhav@cse.ucsc.edu">Contact Us</a>
    </address>
    <\!--end--address-->
    !;
##########################MAIN##################################
#substitute banner tag
&TAG_SUBSTITUTION("banner");
&TAG_SUBSTITUTION("address");


########################SUBROUTINES#############################
#search for <!--$tagName--> in all html files
#if old tag <!--start-$tagName--> present then run until end 
#<!--end-$tagName--> of banner and then print the new one 
sub TAG_SUBSTITUTION
{
    my $tagName = shift;
    ######get all html files######
    chomp(@files = `find ../ -name '*.html'`);
    my $first = 1;
    foreach $file (@files){
	open(file, "<$file");
	open(fileTmp, ">$file.tmp");
	@blurb = <file>;
	foreach $b (@blurb){
	    if ($b =~ /<!--start-$tagName-->/){
		print "oh!\n";
		$first = 0;
	    }
	    if ($b =~ /<!--end-$tagName-->/ ){
		$b = $banner;
		print "auh!\n";
		$first = 1;
	    }
	    if ($b =~ /<!--$tagName-->/ ){
		$b = $$tagName;
		print "$file: $b\n";
	    }
	    if ($first == 1 ){
		print fileTmp $b;
	    }
	}
	close (fileTmp);
	close(file);
	`mv $file.tmp $file`;
    }
}
